### ISSUE TITLE
katello-backup not working with --incremental

### ISSUE THREAD

**Issue by ericlake** [Katello/katello-packaging#358]
Doing some tests today I noticed that I kept seeing the following when doing a incremental backup:
`cp: cannot stat ‘/mnt/katello-backup-2017-01-20T22:32:37+00:00/*.snar’: No such file or directory`

Steps pulled from [here](https://github.com/Katello/katello-packaging/issues/358).

### Full backup command
`katello-backup /mnt/backups/full`

### Incremental backup command
`katello-backup /mnt/backups/monday --incremental /mnt/backups/full`

On the second command is where I saw the the failure about the .snar file. The result was that the full and incremental backups were the same size.

**Comment by lzap** [comment]
This shoud go into 6.2, it is absolutely critical for successful incremental backups. Is there a BZ? Should I create one?

**Comment by lzap** [comment]
https://access.redhat.com/solutions/3015091
