### ISSUE TITLE
rubygem-katello.spec depends on extra packages that are not needed

### ISSUE THREAD

**Issue by cristifalcas** [Katello/katello-packaging#77]
There are a lot of extra packages required by rubygem-katello.spec that, I think, are better suited for katello.spec instead:
# Pulp Requirements

Requires: pulp-katello
Requires: pulp-nodes-parent
Requires: pulp-docker-plugins
Requires: pulp-puppet-plugins
Requires: pulp-rpm-plugins
Requires: pulp-puppet-tools
Requires: pulp-selinux
Requires: pulp-server
Requires: mongodb >= 2.4
Requires: mongodb-server >= 2.4
Requires: cyrus-sasl-plain
Requires: python-crane
Requires: python-gofer-qpid
Requires: qpid-cpp-server-linearstore
Requires: qpid-cpp-client-devel
Requires: qpid-dispatch-router
Requires: candlepin-selinux
Requires: elasticsearch
Requires: createrepo >= 0.9.9-18%{?dist}
Requires: libvirt-devel
Requires: postgresql
Requires: postgresql-server

All of the above can exists on external machines without interfering with katello functionality.

**Comment by ehelms** [comment]
Moved to here http://projects.theforeman.org/issues/12741
